import tkinter as tk
import tkinter.ttk as ttk
import time

window = tk.Tk()
label_1 = tk.StringVar()
Label_1 = tk.Label(window, textvariable=label_1, font=("Arial", 0))
Label_1.grid(column=0, row=5)
label_2 = tk.StringVar()
Label_2 = tk.Label(window, textvariable=label_2, font=("Arial", 0))
Label_2.grid(column=0, row=6)
label_3 = tk.StringVar()
Label_3 = tk.Label(window, textvariable=label_3, font=("Arial", 0))
Label_3.grid(column=0, row=7)
label_4 = tk.StringVar()
Label_4 = tk.Label(window, textvariable=label_4, font=("Arial", 0))
Label_4.grid(column=0, row=8)
label_5 = tk.StringVar()
Label_5 = tk.Label(window, textvariable=label_5, font=("Arial", 0))
Label_5.grid(column=0, row=9)
label_6 = tk.StringVar()
Label_6 = tk.Label(window, textvariable=label_6, font=("Arial", 0))
Label_6.grid(column=0, row=10)
label_7 = tk.StringVar()
Label_7 = tk.Label(window, textvariable=label_7, font=("Arial", 0))
Label_7.grid(column=0, row=11)
label_8 = tk.StringVar()
Label_8 = tk.Label(window, textvariable=label_8, font=("Arial", 0))
Label_8.grid(column=0, row=12)
label_9 = tk.StringVar()
Label_9 = tk.Label(window, textvariable=label_9, font=("Arial", 0))
Label_9.grid(column=0, row=13)
label_10 = tk.StringVar()
Label_10 = tk.Label(window, textvariable=label_10, font=("Arial", 0))
Label_10.grid(column=0, row=14)
label_6.set("Conversion factor")
label_7.set("Shunt resistor")
label_8.set("Time step (seconds)")
label_9.set("Average number")
label_10.set("Time factor")
Txt_box_1 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_1.grid(column=2, row=5)
Txt_box_2 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_2.grid(column=2, row=6)
Txt_box_3 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_3.grid(column=2, row=7)
Txt_box_4 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_4.grid(column=2, row=8)
Txt_box_5 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_5.grid(column=2, row=9)
Txt_box_6 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_6.grid(column=2, row=10)
Txt_box_7 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_7.grid(column=2, row=11)
Txt_box_8 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_8.grid(column=2, row=12)
Txt_box_9 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_9.grid(column=2, row=13)
Txt_box_10 = tk.Entry(window, width=4, state=tk.DISABLED)
Txt_box_10.grid(column=2, row=14)
Adv_btn_txt = tk.StringVar()
Adv_btn_txt.set("Advanced")


def CA_click():
    global Txt_box_1, Txt_box_2, Txt_box_3, Txt_box_4, Txt_box_5
    label_1.set("Voltage (V)")
    label_2.set("Time (seconds)")
    label_3.set("")
    label_4.set("")
    label_5.set("")
    Txt_box_1.config(state=tk.NORMAL)
    Txt_box_2.config(state=tk.NORMAL)
    Txt_box_3.config(state=tk.DISABLED)
    Txt_box_4.config(state=tk.DISABLED)
    Txt_box_5.config(state=tk.DISABLED)

def CV_click():
    label_1.set("Start voltage (V)")
    label_2.set("First turnover voltage")
    label_3.set("Second turnover voltage")
    label_4.set("Sweep rate (mV/s)")
    label_5.set("number of cycles")
    Txt_box_1.config(state=tk.NORMAL)
    Txt_box_2.config(state=tk.NORMAL)
    Txt_box_3.config(state=tk.NORMAL)
    Txt_box_4.config(state=tk.NORMAL)
    Txt_box_5.config(state=tk.NORMAL)

def LSV_click():
    label_1.set("Start voltage (V)")
    label_2.set("Stop voltage")
    label_3.set("Sweep rate (mV/s)")
    label_4.set("")
    label_5.set("")
    Txt_box_1.config(state=tk.NORMAL)
    Txt_box_2.config(state=tk.NORMAL)
    Txt_box_3.config(state=tk.NORMAL)
    Txt_box_4.config(state=tk.DISABLED)
    Txt_box_5.config(state=tk.DISABLED)

def advanced_click():
    if Adv_btn_txt.get() == "Advanced":
        Txt_box_6.config(state=tk.NORMAL)
        Txt_box_7.config(state=tk.NORMAL)
        Txt_box_8.config(state=tk.NORMAL)
        Txt_box_9.config(state=tk.NORMAL)
        Txt_box_10.config(state=tk.NORMAL)
        Adv_btn_txt.set("Hide")
    else:
        Txt_box_6.config(state=tk.DISABLED)
        Txt_box_7.config(state=tk.DISABLED)
        Txt_box_8.config(state=tk.DISABLED)
        Txt_box_9.config(state=tk.DISABLED)
        Txt_box_10.config(state=tk.DISABLED)
        Adv_btn_txt.set("Advanced")



def reset():
    global Label_1, Label_2, Label_3, Label_4, Label_5, label_1, label_2, label_3,\
        label_4, label_5
    Txt_box_1.config(state=tk.NORMAL)
    Txt_box_2.config(state=tk.NORMAL)
    Txt_box_3.config(state=tk.NORMAL)
    Txt_box_4.config(state=tk.NORMAL)
    Txt_box_5.config(state=tk.NORMAL)
    Txt_box_6.config(state=tk.NORMAL)
    Txt_box_7.config(state=tk.NORMAL)
    Txt_box_8.config(state=tk.NORMAL)
    Txt_box_9.config(state=tk.NORMAL)
    Txt_box_10.config(state=tk.NORMAL)
    Txt_box_1.delete(0, tk.END)
    Txt_box_2.delete(0, tk.END)
    Txt_box_3.delete(0, tk.END)
    Txt_box_4.delete(0, tk.END)
    Txt_box_5.delete(0, tk.END)
    Txt_box_6.delete(0, tk.END)
    Txt_box_7.delete(0, tk.END)
    Txt_box_8.delete(0, tk.END)
    Txt_box_9.delete(0, tk.END)
    Txt_box_10.delete(0, tk.END)
    Txt_box_1.config(state=tk.DISABLED)
    Txt_box_2.config(state=tk.DISABLED)
    Txt_box_3.config(state=tk.DISABLED)
    Txt_box_4.config(state=tk.DISABLED)
    Txt_box_5.config(state=tk.DISABLED)
    Txt_box_6.config(state=tk.DISABLED)
    Txt_box_7.config(state=tk.DISABLED)
    Txt_box_8.config(state=tk.DISABLED)
    Txt_box_9.config(state=tk.DISABLED)
    Txt_box_10.config(state=tk.DISABLED)
    label_1.set("")
    label_2.set("")
    label_3.set("")
    label_4.set("")
    label_5.set("")


def start():
    print('run')

window.geometry('500x600')
window.title("Pytentiostat")

lbl_1 = tk.Label(window, text="Enter the test parameters below.", font=("Arial", 0))
lbl_1.grid(column=0, row=0)
lbl_2 = tk.Label(window, text="Experiment type", font=("Arial", 0))
lbl_2.grid(column=0, row=1)

# Experiment buttons and text boxs
CV_btn = tk.Button(window, text="CV", command=CV_click)
CV_btn.grid(column=1, row=1)
LSV_btn = tk.Button(window, text="LSV", command=LSV_click)
LSV_btn.grid(column=2, row=1)
CA_btn = tk.Button(window, text="CA", command=CA_click)
CA_btn.grid(column=3, row=1)
reset_btn = tk.Button(window, text="reset", command=reset).grid(column=5, row=5)
Start_btn = tk.Button(window, text="Start", command=start).grid(column=5, row=6)
Adv_btn = tk.Button(window, textvariable=Adv_btn_txt, command=advanced_click).grid(column=2, row=17)

# Start_btn = tk.Button(window, text="Start", bg="light green", command=btn_click)
# Start_btn.grid(column=4, row=0)

# Text boxes
rest_time_lbl = tk.Label(window, text="rest time (seconds)", font=("Arial", 0))
rest_time_lbl.grid(column=0, row=2)
rest_time_txt = tk.Entry(window, width=4).grid(column=2, row=2)

filename_lbl = tk.Label(window, text="Filename", font=("Arial", 0))
filename_lbl.grid(column=0, row=3)
filename_txt = tk.Entry(window, width=8).grid(column=2, row=3)

file_path_lbl = tk.Label(window, text="Path to data folder", font=("Arial", 0))
file_path_lbl.grid(column=0, row=4)
file_path_txt = tk.Entry(window, width=8).grid(column=2, row=4)

# Show window
window.mainloop()