#!/usr/bin/env python
import argparse
from importlib.metadata import PackageNotFoundError, version

from pytentiostat.main import main


def print_version():
    """Print the version of the pytentiostat package."""
    try:
        pkg_version = version("pytentiostat")
        print(f"Pytentiostat version: {pkg_version}")
    except PackageNotFoundError:
        print("Error: pytentiostat package is not installed.")


def main_wrapper():
    # Set up argument parsing
    parser = argparse.ArgumentParser(
        description="Pytentiostat Command Line Interface"
    )
    parser.add_argument(
        "--version",
        action="store_true",
        help="Show the version of pytentiostat",
    )
    parser.add_argument(
        "--help", action="help", help="Show this help message and exit"
    )

    # Parse the arguments
    args = parser.parse_args()

    # Check if the version flag is set
    if args.version:
        print_version()
    else:
        main()  # Call the main function of the pytentiostat application


if __name__ == "__main__":
    main_wrapper()
